### ISSUE TITLE
Japanese subtitles not working

### ISSUE THREAD

**Issue by r12a** [w3c/presentation-viewer#10]
Maybe it's just not yet been implemented, but whereas i can see the chinese, and korean subtitles for the i18n talk, the japanese doesn't work.

**Comment by dontcallmedom** [comment]
@r12a is that on any talk, or one talk in particular?

**Comment by dontcallmedom** [comment]
also, did you mean the captions on the video, or the ones below the slides in sync mode?

If the former, Japanese captions were missing from many videos as they were under review and corrections; they've now been added (still missing from a few)

**Comment by bert-github** [comment]
This is due to issue #8

**Comment by r12a** [comment]
It tried several talks, and couldn't get the japanese to work with any of them.  

The captions over the video itself never change away from English. I'm talking about the copy of the captions that appears below the slides. (Which does appear to work for Chinese and Korean, where those selections are available.)

**Comment by dontcallmedom** [comment]
fixed
