### ISSUE TITLE
No way to choose translation of long format slide view?

### ISSUE THREAD

**Issue by r12a** [w3c/presentation-viewer#11]
After choosing 'synch video' you can choose to view the transcript in several languages, but when looking at the long page with slides and text you don't seem to be able to.

**Comment by dontcallmedom** [comment]
While we've been able to generate readable English transcripts out of the captions semi-automatically, I couldn't tell how easy/useful these generated captions would be when generated out of Japanese/Chinese/Korean, so we've not attempted to bring the full transcript view in translated versions. If I were to send you the result of this automated generation, would you be in a position to help determine their usefulness?

(the library I'm using has support for building Japanese sentences; but I don't know if it would work for Chinese/Korean, nor if even the Japanese results would be usable)

**Comment by r12a** [comment]
Not sure i understand this.  For the i18n talk you started with a full transcription (in English) which has then been chopped up for presentation as captions.

There are captions in Chinese & Korean.  Did they not come from translations of the full transcript?

**Comment by dontcallmedom** [comment]
the process is actually the reverse - we got English captions done from a captioning service out of the videos; from these captions, we generated the English transcript and associated each section of the transcript with the relevant slide.

We then got the captions translated into our various target languages (by the same captioning service); I could try and generate transcripts out of these captions (by coalescing the captions using the algorithm I have for English, which is supposed to handle Japanese as well), but I don't know how good/usable the result would be. It will also be somewhat tricky (as a non reader or writer of these languages) to do the slide/section association correctly.

**Comment by r12a** [comment]
I see.  

I expect the success will also depend on how the translation was done, especially since it is presumably working on small, incomplete sentences.  Have our staff checked that the translations are understandable and correctly ordered? 

I'd expect the concatenation to mostly work, but you'd need to use different punctuation, and I understand the problem you expect in validating whether the final result of concatenating stuff is correct.  Unfortunately, i can't help with that.

Just a thought: Perhaps it might be useful at some future event to request a french version, so that we could check the quality of the translations and concatenation(?)

**Comment by dontcallmedom** [comment]
we're getting superb help from the Chinese and Japanese teams on reviewing and correcting the translated captions (which have indeed required a lot of corrections so far); we're not sure yet what we can do with regard to Korean ones though.

I'll close this issue for now since I don't think we have a practical way to implement it.
