### ISSUE TITLE
Starting up is not clear...

### ISSUE THREAD

**Issue by iherman** [w3c/presentation-viewer#12]
It was not clear, both on my desktop and on my iPad, what is it that I have to do to start up the presentation. I attach the screen shot of what I see when I start it up; the instinctive reaction is to start the video, which is of course not necessarily what I want. I have to scroll down to find the very tiny button 'Sync video and hide transcript' which then starts the presentation, synced with the slides and the subtitle.

One I find this, it is really good...

![Screen Shot 2020-05-05 at 08 39 12](https://user-images.githubusercontent.com/520723/81040663-2422c900-8eac-11ea-9625-8b8d24a72d8e.png)

**Comment by bert-github** [comment]
One possibility is to first show the video further down, at the level of the sync button. That might remove the urge to start the video before you have seen where the slides are.

(On sufficiently modern browsers I can do this with the, still experimental, 'position: sticky' property.)

**Comment by bert-github** [comment]
I updated the pages to keep the video within the slide/transcript area. Hopefully the interface is clearer like this.
