### ISSUE TITLE
HTML Entities are not shown in subtitles...

### ISSUE THREAD

**Issue by iherman** [w3c/presentation-viewer#14]
The subtitle containing `&amp;` is not resolved into proper `&` sign. See Jeff's presentation at 05:21 (I guess elsewhere, too)

**Comment by dontcallmedom** [comment]
@iherman can you say which of Jeff's presentation?

**Comment by iherman** [comment]
I am sorry. The very first one.

**Comment by dontcallmedom** [comment]
thanks - @bert-github it seems there is indeed double-escaping of the ampersand signs in the captions we generate - in the WebVTT format, ampersands are already escaped

**Comment by bert-github** [comment]
Fixed.
