### ISSUE TITLE
Minor inconsistency on placement...

### ISSUE THREAD

**Issue by iherman** [w3c/presentation-viewer#15]
The slides on PP: for some reasons the line referring to the slides are put on top of the video rather than under the video as for the other presentations...

**Comment by iherman** [comment]
Let me revise that, it is not special to the PP talk.

When I open a page, this is what I see: 

![Screen Shot 2020-05-05 at 10 21 03](https://user-images.githubusercontent.com/520723/81047184-31df4b00-8eba-11ea-9fe7-f9e9cdc4e489.png)

However, when I start playing this, than this is what I see

![Screen Shot 2020-05-05 at 10 22 14](https://user-images.githubusercontent.com/520723/81047263-5804eb00-8eba-11ea-9820-899a5b2827c6.png)

Note the placement of the bar for the video: it switches from underneath to on top. The display means also that the video and the slides are not really side-by-side...

**Comment by bert-github** [comment]
I updated the pages to keep the slide number under the video.
