### ISSUE TITLE
Slide navigation

### ISSUE THREAD

**Issue by SteveALee** [w3c/presentation-viewer#16]
Wow - this is good!!

I'm not sure how to navigate through the slides other than scrolling the page. Sorry If I missed something obvious but the keyboard key says nothing.

I found I wanted to click on the slide number below the video to navigate to that slide.

Or perhasp like Powerpoint/Impress being able to type the slide number to go to it.

And/or a control next to each slide to navigate to that position in the video.

Also, I thought I'd like to be able to navigate forwards/backwards through the slide numbers using that "control". With video and web page scrolling to the correct place (a bit like Web VTT interactive captions)

PS 1st slide does not have a slide number on it - hiding the fact that subsequent slide number occur on the slided themsleves not in the content next to them.

Excellent work indeed!

**Comment by SteveALee** [comment]
Is there supposed to be auto display syncing of the correct slides? One of the email repsonses made me thing there shouldbe. But Jeff tells as to manual move to the slides so I'm not sureif it is expected. I don't get it when playing or scrubbing the video. I tried several videos (Latest Firefox on Windows)

**Comment by SteveALee** [comment]
So Bert explained the sync does work but you have to switch it on.

* The button is a little non obvious and small. Perhaps provide a little styling?
* As the transcript is the default you never see the cool sync at work.

Could the sync still happen with transcript and there is an option to turn the sync off? Ie 2 options or 4 combinations

What do screen reader user prefer?

**Comment by dontcallmedom** [comment]
#12 also points out the difficulty in figuring out the synchronized UI.

Maybe we need a "watch" vs "read" language in here?

**Comment by bert-github** [comment]
Re click on the slide number below the video: Ian also mentioned this in #3. I have it working locally and will publish it soon, after some testing.

Re not finding the sync button: I have (also in test) a style where the video doesn't appear on the first screen, but only next to the slides. I.e., when you first see the video, it will be just to the right of the sync button.

Re sync _with_ transcript: I guess the transcript could optionally scroll up when the video advances to the next slide. But it would be another button to explain.

Re forward/backwards control: When sync is on, there are indeed forward/backwards buttons. I didn't they were needed when you are in scrolling (transcript) mode.

Re type a slide number to jump to it: When the focus is on the video, the number keys are used by the video player to advance by 10% in the video. I think it is better not to use the number keys for something else when the focus is not on the video. (People who have incremental search turned on in their browser already have a conflict, as r12a pointed out elsewhere.)

**Comment by bert-github** [comment]
I updated the pages:

- The slide number under the video is now a link to the slide of that number.

- The video now only appears below the sync button. It should be harder to miss that button now.

**Comment by SteveALee** [comment]
Thanks Bert!
