### ISSUE TITLE
Missing image on a slide?

### ISSUE THREAD

**Issue by iherman** [w3c/presentation-viewer#18]
Jeff's talk on LE, slide 11, talks about an 'endowment card, back and forth', but the slide is empty...

**Comment by swickr** [comment]
Fixed, though this appears to be an issue with the shower script.

@bert-github the combination of <code>class='columns'</code> and <code>height='80%'</code> didn't work (stopped working).

**Comment by bert-github** [comment]
(Height="80%" appears to work in some browsers and not in others. I didn't try to find out which is correct.)

Your solution of expressing the height in 'em' seems a good solution in this case, indeed. I'm going to close the issue.
