### ISSUE TITLE
Can i edit the transcript?

### ISSUE THREAD

**Issue by r12a** [w3c/presentation-viewer#19]
I spent a couple of hours editing the original transcript. There were many places where commas changed the meaning, document titles were not recognised, etc.  So i tried to do a thorough overhaul.  I did miss a couple of items, on rereading today.  

But someone has also introduced some new problems to my edited transcript, which i'd like to fix.

I also noted one typo in the slides. Can i fix that too?

I'm asking in particular because i don't know how that affects the segmentation and display for captions, etc.

---
I'm going to note here some things i noticed so far, to remind me what i want to change. Some of the following produces odd segmentation for the caption text.

Someone changed I18n to I18N, which is against industry practise (and did so inconsistently).

> Slide 23: we also point to the I18N test suite, and you can see here an example of the results page for vertical or some of the vertical text tests.

and 

> Not only were we able to improve the detailed I18N Review Checklist, but we also developed a new self-review checklist that W3C working groups can use to identify areas of their work that are potentially affected by internationalization considerations.

Also introducing some (to me) odd commas in the following, and breaking one sentence into two, after i had joined them.

> The intersection of the language row and the feature column is a colored box that indicates (1), whether we have an issue to address, and (2), what is the severity of that issue if there is one.

and 

> And in these documents we, (1), describe the problem, (2), describe the current level of support in specifications and browsers.

> And (3), we attempt to indicate the severity of the problem for the user.

**Comment by dontcallmedom** [comment]
@r12a as long as you keep the `<div role=region>`, you should be able to edit your transcript as you see fit (it is the `i18n-audio.html` file in the directory of your slides - ping me on IRC if in doubt). Likewise, as long as you don't change the number of slides, feel free to edit your slides.
