### ISSUE TITLE
Session list is not in sync with the order of slides

### ISSUE THREAD

**Issue by iherman** [w3c/presentation-viewer#21]
https://www.w3.org/2020/05/AC/ac-agenda.html#sessions lists the TAG report as part of the Project updates, following PlH's talk. However, if one linearly goes along the presentations following the 'Next: XYZ' buttons, then the TAG talk is linked as the one following Avneesh's presentation.

Also, the Web site redesign talk is the only one linked from that session page...

**Comment by swickr** [comment]
Order of TAG Update corrected.
All talks will be linked once we announce to the AC.
