### ISSUE TITLE
May need to edit Wendy's video

### ISSUE THREAD

**Issue by r12a** [w3c/presentation-viewer#25]
Around 9:10.  Maybe cutting out a few seconds of video there would improve the presentation and better link the intro to the 3 things mentioned.

cc @wseltzer

**Comment by swickr** [comment]
Not impossible but altering the video timing would entail updating all the caption timestamps.

**Comment by dontcallmedom** [comment]
I have a script that can update caption timestamps if necessary

**Comment by wseltzer** [comment]
go for it, and thank you!

**Comment by r12a** [comment]
btw, i was thinking that it might be worth making this presentation available to the public on youtube or something.  Might have to check again for member confidential info, but i don't remember any.  I just remember something that gave a useful overview of the new range of things the W3C does these days, and how we go about bringing things online.

If we did that, however, we'd very much want to remove the bit at 9:10.

**Comment by dontcallmedom** [comment]
@swickr assuming you do edit Wendy's video, if you can give me the exact timecode of the split-off and its exact duration, it will make it very easy to update the captions with my script; we will also have to update the `times.json`.

**Comment by swickr** [comment]
@dontcallmedom video updated.  I trimmed out 4.4 seconds from 09:08.433  to 09:12.847

**Comment by dontcallmedom** [comment]
captions edited (the English one on Streamfizz is stuck for now, expect it to be unstuck shortly)

**Comment by dontcallmedom** [comment]
caption now unstuck, closing
