### ISSUE TITLE
Jeff's sound is off-center

### ISSUE THREAD

**Issue by bert-github** [w3c/presentation-viewer#26]
Daniel discovered that the stereo sound of Jeff's ceo overview is not in the center, but a bit to the left.

**Comment by swickr** [comment]
@daniel-montalvo  I panned the audio a bit to the right; how does this sound to you now?  I did the same for Jeff's other recording.

**Comment by jeffjaffe** [comment]
Thanks @daniel-montalvo, @bert-github , and @swickr .
