### ISSUE TITLE
Add link from "Slide N" to current slide in page

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/presentation-viewer#3]
Hi all,

First of all really nice work on this presentation!

The number of the speaker's current slide appears in a box below the video. My instinct was to click on that "button" to automatically advance to the currently numbered slide. 

Would it be easy to add such links? I consider this "convenient" and not "important."

Thanks!

Ian

**Comment by ianbjacobs** [comment]
Clarification: I mean this for "non-synchronized" mode only.

**Comment by bert-github** [comment]
Making the "Slide N" element into a link should be possible. Making it a link only when the transcript is displayed is hard. The difference between the modes is just in the style sheet, but the style sheet cannot make or remove links. (It used to be possible in Opera, but not anymore...)

**Comment by dontcallmedom** [comment]
done (by @bert-github )

**Comment by ianbjacobs** [comment]
Thanks!
