### ISSUE TITLE
Comcast/Xfinity blocks the video player

### ISSUE THREAD

**Issue by swickr** [w3c/presentation-viewer#36]
Comcast/Xfinity customers with "Advanced Security" enabled receive the message

> "This media is not available"

when trying to view the video.  This is apparently due to

> ***pub.cloud.scaleway.com was blocked as is classified as: Malware

Comcast Customer Support claimed that they do not have a customer-configurable whitelist; the only option is to turn off the Advanced Security feature.

See also #32 

---

Instructions for those affected by this:

1. Sign on to the Xfinity site and click on the wifi symbol.  That will show you your wifi network with an arrow to the right - click that.
2. You should see an Advanced Security block at the top of the next page with an arrow on the right - click the arrow.
3. It will list the devices that have had threats - pick your device and click on the right arrow.
4. It should say "Suspicious Site Visit" with an arrow - click that.
5. There's a bunch of text with a box that says Threat History to the right - click that arrow.
6. On the next page there should be text near the top that says "Want to Access Blocked Sites? - click that.
7. That pops up a window that has a "Go to My Services" button - click that.
8. FINALLY you're on a screen that has a button on the right that lets you turn off Advanced Security.  Click that.

**Comment by swickr** [comment]
Additional from an AC Rep:

> Apparently the site 'pub.cloud.scaleway.com' is described as a 'High Risk' by Brightcloud Threat Intelligence. 

Dom has passed this along to the video platform provider.

**Comment by JohnRiv** [comment]
Sorry this is past the event, but Xfinity customers should now be able to view the videos, as pub.cloud.scaleway.com has been recently rescored and they are now marked as trustworthy.

I've confirmed I can view the videos with Xfinity Advanced Security enabled (I previously could not).

**Comment by swickr** [comment]
Thanks @JohnRiv
