### ISSUE TITLE
Replace generic text with short summary of presentation

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/presentation-viewer#4]
Each page starts with a generic explanatory blurb:

 "This presentation contains a video with optional closed captioning, some slides and a transcript. With the checkbox you can control whether to show all slides or only the slide that the presenter talks about."

I recommend replacing that text with an equally short description of each session. That text can still include a link to the slides below.

Instead of putting the same instructions on every presentation, create a short help page one link away.

Ian

**Comment by bert-github** [comment]
If somebody writes the 2-line summaries for the talks, then I'll make the help page. :-)

**Comment by ianbjacobs** [comment]
The summaries are nice to have but not necessary. Here's an alternative proposal:

* Put the instructions before the first video since that's the first presentation and you want people to see the options.
* For the rest of the presentations, link to those instructions rather than repeating them. 

My main point is that after the first presentation I am unlikely to need the instructions 16 more times.

**Comment by bert-github** [comment]
I removed the intro text and instead put a help link (a circled question mark) at the end of the sync button.

Suggestions for improving the help text welcome!

**Comment by swickr** [comment]
I'm very pleased with the current responsive layout.  But for those who might not notice it without some hint, the help might point out that the video and slides adjust as the window is resized.

In my case, I much prefer the picture-in-picture effect but my default browser window width is just slightly too narrow for that to kick in.  It's a minor action to grow the window a few em horizontally.

**Comment by bert-github** [comment]
I added a hint about wider windows to the help text.

But do the more advanced users read help text? ☺︎
