### ISSUE TITLE
Suggest deleting Next Section links

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/presentation-viewer#5]
I was confused because:

* There is a blue link in the "middle of the page" without any context to suggest its meaning.
* The alt text says "Next section" but I don't know what a section is here. Does it mean the next presentation? (It doesn't.)

I propose the following changes to reduce the risk of confusion:

* The second skip link takes you from the intro to the slides. As I mentioned, there is no context to explain why it is there. Instead, either rely on the "Slides" link that is already in the intro text, or add a "Slides" link somewhere in the metadata section that currently includes the presentation title, Presenter name, and Duration. It can be done elegantly, I'm sure, and when perceived among the metadata, I believe its meaning will be much clearer.
* Delete the "Next section" link that takes you from the start of the slides to the footer. I cannot think of a good reason to navigate to the footer. I thought content might be missing, again confusing me.

Thus, in the end you'll still have a "skip" link at the top to get to the content and a convenient link to slides.

I realize there is some value to having all the arrows line up so that you can click them one after the other. However, it does not seem to me that these areas are primarily for visual browsing, so the ease-of-use with the mouse does not seem to be an important feature.

P.S. Again, fantastic work on this tool. I'm making comments because you inspired me. 😀

**Comment by bert-github** [comment]
I removed the arrows, except for the first and the last.

They are part of the template for the AC and TPAC pages, but on pages with only two sections they are maybe less useful…

**Comment by bert-github** [comment]
I heard no complaints about the absence of the arrows, so I'm closing the issue.
