### ISSUE TITLE
Capture current caption language preference when navigating?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/presentation-viewer#6]
It's AWESOME that captions are being available in different languages. 

My guess is that once a user chooses a caption language, it might be convenient to default to that language preference for all the presentations. I realize there are only about 17 presentations, but it might still be appreciated.

It's probably not worth using cookies. But perhaps you could take a lightweight "most recent user choice wins" approach:

* When the user chooses a caption language, append a query param to both the next and previous presentation links.
* When loading a page, if there's a query param with a caption language value, use it, otherwise default to English.

**Comment by bert-github** [comment]
This is doable. Unless somebody says it's a bad idea, I'll add it.

**Comment by bert-github** [comment]
I updated the pages with this feature. The choice of synchronized/transcript and the caption language are carried over when going to the next or previous page.
